[package]
name = "enel-stop"
version = "0.2.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.3.1"
rss = "2.0.1"
config= "0.13.3"
#replace this with async version
reqwest = { version = "0.11.13", features = ["blocking", "json", "rustls-tls-native-roots"] }
