[package]
name = "enel_stop"
version = "0.9.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.29.1", features = ["full"] }
warp = "0.3.5"

rss = "2.0.5"
config = "0.14.1"
log = "0.4.17"
simple_logger = "5.0.0"
#replace this with async version
reqwest = { version = "0.12.9", features = [
  "blocking",
  "json",
  "rustls-tls-native-roots",
  "cookies",
] }

reqwest_cookie_store = { version = "*" }

serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

redis = "0.27.5"
regex = "1.4.2"
