[package]
name = "enel_stop"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version ="1.29.1", features=["full"] }
warp = "0.3.5"

rss = "2.0.5"
config = "0.13.3"
log = "0.4.17"
simple_logger = "4.0.0"
#replace this with async version
reqwest = { version = "0.11.22", features = [
    "blocking",
    "json",
    "rustls-tls-native-roots",
] }

redis = "0.23.1"
regex = "1.4.2"
