# [package]
# name = "enel_stop"
# version = "0.9.2"
# edition = "2021"

[workspace]
members = ["crawler", "web_server", "common", "browsenscrape"]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
tokio = { version = "1.42.0", features = ["full"] }
warp = "0.3.7"

rss = "2.0.5"
config = "0.15.4"
log = "0.4.17"
simple_logger = "5.0.0"
#replace this with async version
reqwest = { version = "0.12.9", features = [
  "blocking",
  "json",
  "rustls-tls-native-roots",
  "cookies",
] }

reqwest_cookie_store = { version = "*" }

serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

redis = "0.27.6"
regex = "1.4.2"

chrono = "0.4.39"

# headless browse
headless_chrome = { git = "https://github.com/rust-headless-chrome/rust-headless-chrome", features = [
  "fetch",
] }
