#This needs to be copied from the cnpg-cluster namespace manually for now.
apiVersion: v1
kind: Secret
metadata:
  name: enel-db-password
  namespace: enel
type: kubernetes.io/basic-auth
data:
  username: ZW5lbA==
  password: ZW5lbA==
  host: Y25wZy1jbHVzdGVyLXJ3LmNucGctY2x1c3Rlcg==
  name: ZW5lbA==
  port: NTQzMg==
