apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-update
spec:
  template:
    spec:
      containers:
      - name: liquibase
        image: enel-stop-liquibase:latest
        imagePullPolicy: IfNotPresent
        args: ["update"]
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: enel-db-password
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: enel-db-password
              key: port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: enel-db-password
              key: name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: enel-db-password
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: enel-db-password
              key: password
      restartPolicy: Never
  backoffLimit: 3