apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-update
  namespace: cnpg-cluster
spec:
  template:
    spec:
      containers:
      - name: liquibase
        image: ghcr.io/homelab1025/enel-stop-liquibase:latest
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args:
          - -c
          - |
            export LIQUIBASE_COMMAND_URL="jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
            export LIQUIBASE_COMMAND_USERNAME="${DB_USER}"
            export LIQUIBASE_COMMAND_PASSWORD="${DB_PASSWORD}"
            liquibase update
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: enel-db-password
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: enel-db-password
              key: port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: enel-db-password
              key: name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: enel-db-password
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: enel-db-password
              key: password
      restartPolicy: Never
  backoffLimit: 3