apiVersion: apps/v1
kind: Deployment
metadata:
  name: seleniumbase
  labels:
    app: seleniumbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seleniumbase
  template:
    metadata:
      name: seleniumbase
      labels:
        app: seleniumbase
    spec:
      containers:
        - name: seleniumbase
          image: seleniumbase/seleniumbase:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4444
              protocol: TCP
            - containerPort: 7900
              protocol: TCP
          env:
            - name: SE_NODE_MAX_SESSIONS
              value: "4"
            - name: SE_NODE_SESSION_TIMEOUT
              value: "300"
            - name: SE_VNC_NO_PASSWORD
              value: "1"
            - name: SE_OPTS
              value: "--disable-dev-shm-usage"
            - name: SE_CDP_MODE
              value: "true"
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
      restartPolicy: Always