apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: selenium

resources:
- selenium-deployment.yaml
- selenium-service.yaml
- selenium-hub-deployment.yaml
- selenium-hub-service.yaml
- namespace.yaml

commonLabels:
  app.kubernetes.io/part-of: selenium-grid
