apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: selenium

resources:
- selenium-deployment.yaml
- selenium-service.yaml

commonLabels:
  app.kubernetes.io/name: selenium-chrome
  app.kubernetes.io/part-of: selenium-grid
