apiVersion: v1
kind: Namespace
metadata:
  name: enel
  labels:
    name: enel
    # pod-security.kubernetes.io/enforce: restricted
    istio-injection: enabled


# Warning: would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "enel-web" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "enel-web" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "enel-web" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "enel-web" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enel-web
  namespace: enel
spec:
  selector:
    matchLabels:
      app: enel-web
  replicas: 3
  template:
    metadata:
      labels:
        app: enel-web
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: enel-web
        image: ghcr.io/fdiaconeasa/enel-stop-web:v0.9.0
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        resources:
          limits:
            memory: "64Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: enel-web
  namespace: enel
spec:
  selector:
    app: enel-web
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enel-web-api
  labels:
    name: enel-web-api
  namespace: enel
spec:
  ingressClassName: nginx
  rules:
  - host: enel.k8s.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: enel-web
            port: 
              number: 8080
