apiVersion: v1
kind: Namespace
metadata:
  name: enel
  labels:
    name: enel

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enel-web
  namespace: enel
spec:
  selector:
    matchLabels:
      app: enel-web
  replicas: 3
  template:
    metadata:
      labels:
        app: enel-web
    spec:
      containers:
      - name: enel-web
        image: image-registry:5000/enel/web:0.6.1
        resources:
          limits:
            memory: "64Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: enel-web
  namespace: enel
spec:
  selector:
    app: enel-web
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enel-web-api
  labels:
    name: enel-web-api
  namespace: enel
spec:
  ingressClassName: nginx
  rules:
  - host: enel.k8s.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: enel-web
            port: 
              number: 8080
