apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  namespace: cnpg-cluster
spec:
  template:
    spec:
      containers:
        - name: migration
          image: ghcr.io/homelab1025/enel-stop-migration:latest
          imagePullPolicy: Always
          env:
            - name: APP_service_db_host
              valueFrom:
                secretKeyRef:
                  key: host
                  name: enel-db-password
            - name: APP_service_db_name
              valueFrom:
                secretKeyRef:
                  key: name
                  name: enel-db-password
            - name: APP_service_db_password
              valueFrom:
                secretKeyRef:
                  key: password
                  name: enel-db-password
            - name: APP_service_db_username
              valueFrom:
                secretKeyRef:
                  key: username
                  name: enel-db-password
      restartPolicy: Never
  backoffLimit: 4
