[service]
log_level = "Debug"
url = "https://www.reteleelectrice.ro/rss-outages.xml/"
# pushgateway_server = "https://prometheus-pushgateway-prometheus"
http_port = 8080
cors_permissive = true
web_server_address = "http://enel-web.enel:8080/scraper"

db_host = "cnpg-cluster-rw.cnpg-cluster"
db_port = 5432
db_name = "enel"

[filter]
categories = []
