[service]
url = "https://www.reteleelectrice.ro/content/dam/retele-electrice/outages/rss/enel_rss_muntenia.xml"
refresh_ms = 5000
redis_server = "127.0.0.1"

[filter]
categories = []

[storage]
redis.server = "redis-master.redis"
redis.space = "enel"

[notifs]
auth_token = "aaaa"
