[service]
log_level = "info"
url = "https://www.reteleelectrice.ro/rss-outages.xml/"
pushgateway_server = "http://prometheus-pushgateway.monitoring.svc.cluster.local:9091/metrics/job/enel"
http_port = 8080
cors_permissive = true
web_server_address = "http://enel-web.enel:8080/scraper"
db_host = "cnpg-cluster-rw.cnpg-cluster"
db_port = 5432
db_name = "enel"

[filter]
categories = []
