[service]
url = "https://www.e-distributie.com/content/dam/e-distributie/outages/rss/enel_rss_muntenia.xml"
refresh_ms = 60000

[filter]
categories = ["Jud. ILFOV", "POPESTI LEORDENI"]

[notifs]
auth_token = "aaaa"