[service]
url = "https://www.reteleelectrice.ro/content/dam/retele-electrice/outages/rss/enel_rss_muntenia.xml"
refresh_ms = 60000
redis.server = "redis-master.redis"

[filter]
categories = ["Jud. ILFOV"]

[notifs]
auth_token = "aaaa"

[storage]
redis.space = "enel"

