[service]
url = "https://www.e-distributie.com/content/dam/e-distributie/outages/rss/enel_rss_muntenia.xml"
refresh_ms = 5000
redis_server = "127.0.0.1"

[filter]
categories = ["Jud. ILFOV"]

[storage]
redis.server = "127.0.0.1:9090"
redis.space = "enel"

[notifs]
auth_token = "aaaa"
