[service]
url = "https://www.reteleelectrice.ro/content/dam/retele-electrice/outages/rss/enel_rss_muntenia.xml"
redis_server = "redis://enel-redis-master/"
store_enabled = false

[filter]
categories = []

[notifs]
auth_token = "aaaa"

[storage]
redis.space = "enel"
