log_level = "Debug"

[service]
url = "https://www.reteleelectrice.ro/rss-outages.xml/"
#redis_server = "redis://192.168.23.107/"
# pushgateway_server = "https://prometheus-pushgateway-prometheus"
http_port = 8080
cors_permissive = true
web_server_address = "http://enel-web.enel:8080/scraper"

[filter]
categories = []
