[service]
url = "https://www.reteleelectrice.ro/intreruperi/programate/"
refresh_ms = 5000
# redis_server = "127.0.0.1"
# store_enabled = false

[filter]
categories = []

[storage]

[notifs]
auth_token = "aaaa"
