[package]
name = "web_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
common = { path = "../common" }
simple_logger = { workspace = true }
log = { workspace = true }
axum = { workspace = true }
redis = { workspace = true }
serde_json = { workspace = true }
testcontainers = { workspace = true }
chrono = { workspace = true }