apiVersion: apps/v1
kind: Deployment
metadata:
  name: enel-web
  labels:
    app: enel-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enel-web
  template:
    metadata:
      name: enel-web
      labels:
        app: enel-web
    spec:
      containers:
        - name: enel-web
          image: ghcr.io/homelab1025/enel-stop-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config.toml
              name: web-config-file
              subPath: config.toml
          env:
            - name: APP_service-db_host
              valueFrom:
                secretKeyRef:
                  key: host
                  name: enel-db-password
            - name: APP_service-db_name
              valueFrom:
                secretKeyRef:
                  key: name
                  name: enel-db-password
            - name: APP_service-db_password
              valueFrom:
                secretKeyRef:
                  key: password
                  name: enel-db-password
            - name: APP_service-db_username
              valueFrom:
                secretKeyRef:
                  key: username
                  name: enel-db-password
      restartPolicy: Always
      volumes:
        - name: web-config-file
          configMap:
            name: web-config
      