apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enel-webapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: enel.lab.wicked
      http:
        paths:
          - path: /web
            pathType: Prefix
            backend:
              service:
                name: enel-webapp
                port:
                  number: 8080
