apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enel-web
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: enel.lab.wicked
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: enel-web
                port:
                  number: 80
