name: Create AMD64 image

on:
  push:
    tags: ['*']
    branches: ["master"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: enel-stop-runners
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker (crawler)
        id: meta-crawler
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-crawler

      - name: Build and push Docker image for crawler
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          target: crawler
          tags: ${{ steps.meta-crawler.outputs.tags }}
          labels: ${{ steps.meta-crawler.outputs.labels }}
      
      - name: Extract metadata (tags, labels) for Docker (web)
        id: meta-web
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-web

      - name: Build and push Docker image for web service
        uses: docker/build-push-action@v4
        with:
         context: .
         platforms: linux/amd64
         push: true
         target: web
         tags: ${{ steps.meta-web.outputs.tags }}
         labels: ${{ steps.meta-web.outputs.labels }}

