name: Rust

on:
  push:
    tags: ['*']
    branches: [ "master" ]
env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test
    - name: Build
      run: cargo build --release
    - name: Build API spec
      run: cargo run -p api_gen

  build-and-push-image-server:
    runs-on: self-hosted
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker (crawler)
        id: meta-crawler
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-crawler

      - name: Build and push Docker image for crawler
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          target: crawler
          tags: ${{ steps.meta-crawler.outputs.tags }}
          labels: ${{ steps.meta-crawler.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker (web)
        id: meta-web
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-web

      - name: Build and push Docker image for web service
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          target: web
          tags: ${{ steps.meta-web.outputs.tags }}
          labels: ${{ steps.meta-web.outputs.labels }}

  build-and-push-webapp:
    runs-on: self-hosted
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Generate TS sources
        run: openapi-generator generate -g typescript-axios -i openapi.yml -o webapp/src/lib/server/
      - name: Install dependencies
        working-directory: ./webapp
        run: npm install
      - name: Build Webapp
        working-directory: ./webapp
        run: npm run build

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker (webapp)
        id: meta-webapp
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-webapp

      - name: Build and push Docker image for web app
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          target: webapp
          tags: ${{ steps.meta-webapp.outputs.tags }}
          labels: ${{ steps.meta-webapp.outputs.labels }}
