name: Rust

on:
  push:
    tags: ['*']
    branches: [ "master" ]
env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  OPENAPI_SPEC_PATH: "target/release/openapi.yaml"
  CACHED_PATHS: |
    target/release/browsenscrape
    target/release/migration
    target/release/web_server
    target/release/openapi.yaml

jobs:

  build:
    runs-on: self-hosted
    outputs:
      release_version: ${{ steps.set_version.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set Release Version
      id: set_version
      run: |
        # Generate a version string. You can customize this.
        # Examples:
        #  - Short SHA: version=$(git rev-parse --short HEAD)
        #  - Run number and short SHA: version="${{ github.run_number }}-${{ github.sha }}"
        # For a release on each commit, using a timestamp or run number + short SHA is good.
        VERSION=$(date +'%Y%m%d%H%M%S')-${{ github.sha }}
        echo "Generated Release Version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash
    - name: Cache rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run tests
      run: cargo test
    - name: Build
      run: cargo build --release
    - name: Build API spec
      run: target/release/api_gen ${{env.OPENAPI_SPEC_PATH}}
    - name: Cache target
      uses: actions/cache@v4
      with:
        key:  target-${{ github.run_id }}-${{ github.run_attempt }}
        path: ${{env.CACHED_PATHS}}

  build-scraper:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache target
        uses: actions/cache@v4
        with:
          key: target-${{ github.run_id }}-${{ github.run_attempt }}
          path: ${{env.CACHED_PATHS}}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for python scraper
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          target: scraper
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-scraper:v${{ needs.build.outputs.release_version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-scraper:latest

  build-and-push-image-crawler:
    runs-on: self-hosted
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache target
        uses: actions/cache@v4
        with:
          key: target-${{ github.run_id }}-${{ github.run_attempt }}
          path: ${{env.CACHED_PATHS}}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for crawler
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          target: crawler
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-crawler:v${{ needs.build.outputs.release_version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-crawler:latest

  build-and-push-image-webservice:
    runs-on: self-hosted
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache target
        uses: actions/cache@v4
        with:
          key: target-${{ github.run_id }}-${{ github.run_attempt }}
          path: ${{env.CACHED_PATHS}}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for web service
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          target: web
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-web:v${{ needs.build.outputs.release_version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-web:latest

  build-and-push-image-migration:
    runs-on: self-hosted
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache target
        uses: actions/cache@v4
        with:
          key: target-${{ github.run_id }}-${{ github.run_attempt }}
          path: ${{env.CACHED_PATHS}}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for migration
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          target: migration
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-migration:v${{ needs.build.outputs.release_version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-migration:latest

  build-and-push-webapp:
    runs-on: self-hosted
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache target
        uses: actions/cache@v4
        with:
          key: target-${{ github.run_id }}-${{ github.run_attempt }}
          path: ${{env.CACHED_PATHS}}
      - name: Generate TS sources
        run: openapi-generator generate -g typescript-axios -i ${{env.OPENAPI_SPEC_PATH}} -o webapp/src/lib/server/
      - name: Install dependencies
        working-directory: ./webapp
        run: npm install
      - name: Build Webapp
        working-directory: ./webapp
        run: npm run build

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for web app
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          target: webapp
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-webapp:v${{ needs.build.outputs.release_version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-webapp:latest
