apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- service-patch.yaml

namePrefix: local-
namespace: selenium

commonLabels:
  environment: local